---
- name: Prepare database server
  hosts: dbservers
  become: true
  roles:
    - role: postgresql
      tags: [prepare, deploy]

- name: Prepare and deploy web application
  hosts: webservers
  become: true
  roles:
    - role: docker
      tags: [prepare, deploy]
    - role: redmine
      tags: [deploy]

- name: Install Datadog agent on webservers
  hosts: webservers
  become: true
  roles:
    - role: monitoring_datadog
      tags: [monitoring]

- name: Prepare and configure load balancer
  hosts: lbservers
  become: true
  roles:
    - role: loadbalancer
      tags: [prepare, deploy]
